name: medfast_go
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4
  flutter_typeahead: ^3.1.1
  shared_preferences: ^2.0.9
  intl_phone_number_input: ^0.7.3+1
  cupertino_icons: ^1.0.2
  geolocator: ^8.0.0
  http: ^0.13.3
  permission_handler: ^8.0.1
  intl: ^0.17.0
  sqflite: ^2.0.0
  path_provider_foundation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Medrxlogo.png
    - lib/assets/Successmark.png
    - lib/assets/medicine.png
    - lib/assets/Financial Insights.png
    - lib/assets/medlaunchinglogo.png
    - lib/assets/Posimage.png
    - lib/assets/no_barcode_icon.png
    - lib/assets/barcode_icon.png